[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@uniswap/=lib/",
    "@uniswap-v2-periphery/=lib/v2-periphery",
    "@uniswap-v3-periphery/=lib/v3-periphery",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
